blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('list/', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>', toggle_activity, name='toggle_activity'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, dociment_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    Heading = models.CharField(max_length=90, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    Content = models.CharField(max_length=300, verbose_name='Содержимое')
    image = models.ImageField(upload_to='products/', verbose_name='изображение (превью)', **NULLABLE)
    date_of_creation = models.DateField(default=timezone.now, verbose_name='дата создания')
    is_active = models.BooleanField(default=True, verbose_name='признак публикации')
    view_count = models.IntegerField(default=0, verbose_name='Счетчик просмотров')

    def __str__(self):
        return f'{self.Heading}, {self.Content}, {self.date_of_creation}, {self.is_active}'

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('Heading', 'Content', 'image', 'is_active',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.Heading)
            new_blog.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_active=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.blog = super().get_object(queryset)
        self.blog.view_count += 1
        self.blog.save()
        return self.blog


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('Heading', 'slug', 'Content', 'image', 'date_of_creation', 'is_active', 'view_count',)

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.Heading)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:list')


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')


def toggle_activity(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_active:
        blog_item.is_active = False
    else:
        blog_item.is_active = True

    blog_item.save()

    return redirect(reverse('blog:list'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Вы действительно хотите удалить статью?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning">
                            Отмена
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12">
    <div class="card mb-3 box-shadow">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">{{ blog.Heading }} ({{ blog.slug }})</h4>
        </div>
        <div class="card-body">
          <ul class="list-unstyled mt-3 mb-4 text-start m-3">
              {{blog.Content}}
              <img class="card-img-top"
              src="{% mediapath blog.image %}"
              alt="Card image cap" />
          </ul>
          <ul  class="list-unstyled mt-3 mb-4 text-start m-3">{{ blog.date_of_creation}}</ul >
          <ul  class="list-unstyled mt-3 mb-4 text-start m-3">{{ blog.is_active}}</ul >
          <ul class="list-unstyled mt-3 mb-4 text-start m-3">{{ blog.view_count}}</ul>
          <ul class="list-unstyled mt-3 mb-4 text-start m-3"></ul>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-primary mt-3 mb-4">
                            {% if blog %}
                            Сохранить
                            {% else %}
                            Создать статью
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

    <a class="btn btn-outline-primary mt-3 mb-4" href="{% url 'blog:create'%}">Создать статью</a>

{% for blog in blog_list %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ blog.Heading }}</h4>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                {{blog.Content | first_100}}
                <img class="card-img-top"
                src="{% mediapath blog.image %}"
                alt="Card image cap" />
            </ul>
            <ul  class="list-unstyled mt-3 mb-4 text-start m-3">{{ blog.date_of_creation}}</ul >
            <ul  class="list-unstyled mt-3 mb-4 text-start m-3">{{ blog.is_active}}</ul >
            <ul class="list-unstyled mt-3 mb-4 text-start m-3"></ul>
            <div class="acrd-footer">
                Просмотры: {{ blog.view_count}}

            </div>
            <form action="" method="post">
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:view' blog.pk %}">Просмотреть</a>
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:edit' blog.pk %}">Изменить</a>
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:delete' blog.pk %}">Удалить</a>
                <a class="btn btn-sm btn-warning" href="{% url 'blog:toggle_activity' blog.pk %}">Деактиввировать</a>
            </form>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}