blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('list/', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>', toggle_activity, name='toggle_activity'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, dociment_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, EmailVerifyView, UserFormView, create_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_email/', EmailVerifyView.as_view(), name='verify_email'),
    path('user_form/', UserFormView.as_view(), name='user_form'),
    path('user_form/create_new_password/', create_new_password, name='create_new_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from random import randint

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')
    avatar = models.ImageField(upload_to='media/users/', verbose_name='аватар', **NULLABLE)
    phone = models.IntegerField(verbose_name='Номер телефона',  **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='Страна',  **NULLABLE)
    email_verify = models.BooleanField(default=False, verbose_name='подтверждение почты')
    key = models.CharField(max_length=4, default=randint(1000, 9999), verbose_name='ключ регистрации')

    USERNAME_FIELD ="email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return (f'{self.email} {self.phone} {self.country}')

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

users/views.py
from random import randint

from django.conf import settings
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, TemplateView, UpdateView

from users.forms import UserForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    """
    Регистрация и отправка на почту ключа
    """
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:verify_email')
    template_name = 'users/register.html'

    def form_valid(self, form):
        new_user = form.save()
        new_user.is_active = False
        new_user.save()
        send_mail(
            subject='Подтвердите регистрацию',
            message=f'Вы зарегистрировались, теперь подтвердите резистрацию\n '
                    f'http://127.0.0.1:8000/verify_email/\n'
                    f'{new_user.key}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email],
        )
        return super().form_valid(form)


class EmailVerifyView(TemplateView):
    """
    Проверка ключа регистрации, если ключ совпадает то пользователь прошел верификацию
    """
    template_name = 'users/verify_email.html'

    def post(self, request):
        key = request.POST.get('key')
        user_code = User.objects.filter(key=key).first()

        if user_code is not None and user_code.key == key:
            user_code.email_verify = True
            user_code.is_active = True
            user_code.save()
            return redirect('users:login')
        else:
            user_code.is_active = False
            return redirect('users:verify_email')


class UserFormView(UpdateView):
    model = User
    success_url = reverse_lazy('users:user_form')
    fields = '__all__'

    def get_object(self, queryset=None):
        return self.request.user


def create_new_password(request):
    """
    Смена пароля и отправка на почту нового пароля
    """
    new_password = ''.join([str(randint(0, 9)) for i in range(8)])
    request.user.set_password(new_password)
    request.user.save()
    send_mail(
        subject='Новый пароль',
        message=f'{new_password}\n ',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email],
    )
    return redirect(reverse('users:login'))

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                    <div class="card-header">
                        <h3 class="card-title mt-2 mb-2" >
                            Вход
                        </h3>
                    </div>
                <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-primary mt-2 mb-2">войти</button>

                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                    <div class="card-header">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div>
                <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-primary mt-3 mb-4">
                            зарегистрироваться
                        </button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-header">
                    <h3 class="card-title">
                        Профиль
                    </h3>
              </div>
              <div class="card-body">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <a class="btn btn-outline-primary mt-2 mb-2" href="{% url 'users:create_new_password' %}">Создать пароль</a>
              </div>
              <div class="card-footer">
                  <button type="submit" class="btn btn-success" >Сохранить</button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/verify_email.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-header">
                    <h3 class="card-title">
                        Введите код
                    </h3>
                </div>
                <div class="card-body">
                  {% csrf_token %}
                  <input type="text" name="key" class="form-control" id="key" required>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-success">Подтвердить</button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}