blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('list/', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>', toggle_activity, name='toggle_activity'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, choice_status

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('<int:pk>/product/', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('create_product/', ProductCreateView.as_view(), name='create_product'),
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('edit_product/<int:pk>', ProductUpdateView.as_view(), name='edit_product'),
    path('delete_product/<int:pk>', ProductDeleteView.as_view(), name='delete_product'),
    path('status_product/<int:pk>', choice_status, name='status_product'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, dociment_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.utils import timezone

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):

    STATUS_published = 'published'
    STATUS_not_published = 'not_published'
    STATUSES = [
        (STATUS_published, 'опубликовано'),
        (STATUS_not_published, 'не опубликовано'),
    ]

    name = models.CharField(max_length=90, verbose_name='наименование')
    description = models.CharField(max_length=300, verbose_name='описание')
    image = models.ImageField(upload_to='products/', verbose_name='изображение (превью)', **NULLABLE)
    category = models.CharField(max_length=90, verbose_name='категория')
    purchase_price = models.IntegerField(verbose_name='цена за покупку')
    date_of_creation = models.DateTimeField(default=timezone.now, verbose_name='дата создания')
    last_modified_date = models.DateTimeField(default=timezone.now, verbose_name='дата последнего изменения')
    user = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE)
    is_published = models.CharField(max_length=20, default=STATUS_not_published, verbose_name='статус публикации',  choices=STATUSES)

    def __str__(self):
        return (f'{self.name} {self.description} {self.category} '
                f'{self.purchase_price} {self.date_of_creation} {self.last_modified_date} {self.is_published}')

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        permissions = [
            (
                'set_published',
                'can published posts'
            ),
            (
                'change_description',
                'Can change description'
            ),
            (
                'set_category',
                'Can set category'
            )
        ]


class Category(models.Model):
    name = models.CharField(max_length=90, verbose_name='наименование')
    description = models.CharField(max_length=300, verbose_name='описание')

    def __str__(self):
        return (f'{self.name} {self.description}')

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Version(models.Model):
    name_product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    version_number = models.IntegerField(verbose_name='номер версии')
    name_version = models.CharField(max_length=90, verbose_name='название версии')
    flag_of_the_cur_ver = models.BooleanField(verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.name_product} {self.version_number} {self.name_version}  {self.flag_of_the_cur_ver}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version

bad_name = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StileFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'flag_of_the_cur_ver':
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StileFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        for name in bad_name:
            if name in cleaned_data.lower():
                raise forms.ValidationError('Название продукта содержит запрещенные значения')
        return cleaned_data


class ModerProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('is_published', 'description', 'category')


class VersionForm(StileFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ModerProductForm
from catalog.models import Product, Version
from catalog.services import cache_category


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/home.html'


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Получено сообщение: {name}, ({phone}): {message}')
    return render(request, 'catalog/contacts.html')


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product.html'


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        if form.is_valid:
            new_product = form.save()
            new_product.user = self.request.user
            new_product.save()

    def get_success_url(self):
        return reverse('catalog:product_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_queryset(self):
        """возвращаем кэш с категориями"""
        return cache_category


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'
    success_url = reverse_lazy('catalog:product_list')

    def get_success_url(self):
        return reverse('catalog:product_list')

    def get_queryset(self):
        return super().get_queryset().filter(id=self.kwargs.get('pk'), user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        product_item = Product.objects.get(pk=self.kwargs.get('pk'))
        context_data['product_pk'] = product_item.pk

        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if (self.request.user != self.object.user and not self.request.user.is_staff and
                not self.request.user.is_superuser and self.request.user.has_perm('catalog.set_published')):
            raise Http404
        return self.object

    def get_form_class(self):
        if self.request.user.has_perm('catalog.set_published') and not self.request.user.is_superuser:
            return ModerProductForm
        return ProductForm


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')


@login_required
@permission_required
def choice_status(requsest, pk):
    product_item = get_object_or_404(Product, pk=pk)
    if product_item.is_published == "published":
        product_item.is_published = "not_published"
    else:
        product_item.is_published = "published"
    product_item.save()

    return redirect(reverse('catalog:product_list'))

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
        <!-- подключение статического CSS-файла -->
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

<!-- подключение статического JS-файла -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
   {% include 'catalog/includes/inc_head_menu.html'%}
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        {% block content %}
        {% endblock %}
    </div>


    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src= "{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required />
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required />
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <div>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
        {% for product in product_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ product.purchase_price}}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        {{product.description | first_100}}
                        <img class="card-img-top"
                        src="{% mediapath product.image %}"
                        alt="Card image cap" />
                    </ul>
                    <form action="" method="post">
                        <a class="btn btn-outline-primary" href="{% url 'catalog:product' product.pk %}">Купить</a>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
        <div class="col-12">
            <div class="card mb-3 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">Цена:{{ product.purchase_price}} руб</h1>
                    <li>{{ product.description}}</li>
                    <li>Категория: {{ product.category}}</li>
                    <li>Дата создания: {{ product.date_of_creation}}</li>
                    <li>Дата последнего изменения: {{ product.last_modified_date}}</li>
                    <img class="card-img-top"
                    src="{% mediapath product.image %}"
                    alt="Card image cap" />
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Вы действительно хотите удалить продукт?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-warning">
                            Отмена
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
        <div class="col-12">
            <div class="card mb-3 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">Цена:{{ product.purchase_price}} руб</h1>
                    <li>{{ product.description}}</li>
                    <li>Категория: {{ product.category}}</li>
                    <li>Дата создания: {{ product.date_of_creation}}</li>
                    <li>Дата последнего изменения: {{ product.last_modified_date}}</li>
                    <img class="card-img-top"
                    src="{% mediapath product.image %}"
                    alt="Card image cap" />
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                    <div class="card-header">
                        <h3 class="card-title">
                            добавление товара
                        </h3>
                    </div>
                <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-primary mt-3 mb-4">
                            {% if product %}
                            Сохранить
                            {% else %}
                            Добавить продукт
                            {% endif %}
                        </button>
                </div>
            </div>
            <div class="col-6">
                <div class="card-header">
                        <h3 class="card-title">
                            версии товаров
                        </h3>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
        <a class="btn btn-outline-primary mt-3 mb-4" href="{% url 'catalog:create_product'%}">Добавить продукт</a>
        {% for product in product_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ product.purchase_price}}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        {{product.description | first_100}}
                        <img class="card-img-top"
                        src="{% mediapath product.image %}"
                        alt="Card image cap" />
                    </ul>
                    <form action="" method="post">
                        <a class="btn btn-sm btn-outline-secondary mt-3 mb-2" href="{% url 'catalog:product' product.pk %}">Просмотреть</a>
                        {% if perms.catalog.change_product %}
                        <a class="btn btn-sm btn-outline-secondary mt-3 mb-2" href="{% url 'catalog:edit_product' product.pk %}">Изменить</a>
                        {% endif %}
                        {% if perms.catalog.delete_product %}
                        <a class="btn btn-sm btn-outline-secondary mt-3 mb-2" href="{% url 'catalog:delete_product' product.pk %}">Удалить</a>
                        {% endif %}
                        {% if perms.catalog.published_posts %}
                        {% if product.is_published == "published" %}
                        <a class="btn btn-sm btn btn-warning mt-3 " href="{% url 'catalog:status_product' product.pk %}">Снять с публикации</a>
                        {% else %}
                        <a class="btn btn-sm btn btn-success mt-3 " href="{% url 'catalog:status_product' product.pk %}">Опубликовать</a>
                        {% endif%}
                        {% endif %}

                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
{% endblock %}